# Generated by Django 4.2.7 on 2023-11-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comente_sobres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
